name: icongrega
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  fluttertoast: ^9.0.0
  google_fonts: ^6.1.0
  image_picker: ^1.2.0
  share_plus: ^12.0.0
  video_player: ^2.10.0
  visibility_detector: ^0.4.0+2
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  flutter_spinkit: ^5.2.2
  skeletonizer: ^2.1.0+1
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  connectivity_plus: ^7.0.0
  flutter_dotenv: ^6.0.0
  flutter_svg: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/religion/
    - assets/images/two-factor/
    - assets/images/forgot-password/
    - assets/images/my-password/
    - .env

